rm(list=ls())
library(chron)
library(dplyr)
library(lubridate)
setwd("./Exploratory Data Analysis")
epc<-read.table("household_power_consumption.txt",sep = ";",header = TRUE, na.strings = "?")
epc$Date<-as.Date(epc$Date,format = "%d/%m/%Y")
epc$Time<-chron(times=epc$Time)
feb_epc<-filter(epc,Date=="2007-02-01" | Date=="2007-02-02")

feb_epc$datime<-as.POSIXlt(paste(feb_epc$Date,feb_epc$Time),format="%Y-%m-%d %H:%M:%OS")
png("plot2.png")
with(feb_epc,plot(datime,Global_active_power,type="l",ylab = "Global Active Power (kilowatts)",xlab=""))
dev.off()